# Generated by Django 4.2.7 on 2025-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_carrier_created_by_remove_client_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="imap_use_ssl",
            field=models.BooleanField(default=True, verbose_name="Использовать SSL для IMAP"),
        ),
    ]
