version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - backend_deps:/app/venv
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=your_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,185.135.83.113
    ports:
      - "8000:8000"
    command: >
      sh -c "python -m venv venv && 
             . venv/bin/activate && 
             pip install --upgrade pip && 
             pip install -r requirements.txt && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - app_network
    expose:
      - 8000

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_deps:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: npm start
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - app_network
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
    restart: always

volumes:
  backend_deps:
    driver: local
  frontend_deps:
    driver: local
  static_volume:
    driver: local
  media_volume:
  frontend_node_modules:

networks:
  app_network:
    driver: bridge 