version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - backend_deps:/app/venv
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=your_secret_key
    ports:
      - "8000:8000"
    command: >
      sh -c "python -m venv venv && 
             . venv/bin/activate && 
             pip install -r requirements.txt && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_deps:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://185.135.83.113:8000/api
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: npm start
    restart: always

volumes:
  backend_deps:
  frontend_deps:

  static_volume:
  media_volume:
  frontend_node_modules:

networks:
  app_network:
    driver: bridge 