version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      - ./backend:/app
      - backend_deps:/app/venv
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=your_secret_key
    ports:
      - "8000:8000"
    command: >
      sh -c "python -m venv venv && 
             . venv/bin/activate && 
             pip install --upgrade pip && 
             pip install -r requirements.txt && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      - ./frontend:/app
      - frontend_deps:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://185.135.83.113:8000/api
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - "3000:3000"
    command: npm start
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:
  backend_deps:
  frontend_deps:

  static_volume:
  media_volume:
  frontend_node_modules:

networks:
  default:
    driver: bridge 