version: '3.8'

services:
  db:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=c64s6KPa
      - MARIADB_DATABASE=logistic_crm
      - MARIADB_USER=greatline_root
      - MARIADB_PASSWORD=c64s6KPa
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media:delegated
    environment:
      - DJANGO_SETTINGS_MODULE=logistic_crm.settings
      - DJANGO_SECRET_KEY=your-secret-key
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgres://greatlineby_root:c64s6KPa!@db:5432/greatlineby_crm
      - EMAIL_ENCRYPTION_KEY=jaj9qouzOs-ACsia3xikjwEvv9es_3lzoKF6Csei8-4=
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:
  static_volume:
  media_volume:
  frontend_node_modules:

networks:
  app_network:
    driver: bridge 