# Generated by Django 5.1.7 on 2025-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_key", models.CharField(max_length=255, verbose_name="API ключ")),
                (
                    "model",
                    models.CharField(default="google/gemini-flash-1.5-8b", max_length=100, verbose_name="Модель"),
                ),
                (
                    "base_url",
                    models.CharField(
                        default="https://openrouter.ai/api/v1", max_length=255, verbose_name="Базовый URL"
                    ),
                ),
                ("max_tokens", models.IntegerField(default=500, verbose_name="Максимальное количество токенов")),
                ("temperature", models.FloatField(default=0.7, verbose_name="Температура")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки AI",
                "verbose_name_plural": "Настройки AI",
            },
        ),
    ]
